const now = new Date()
const isoMinusMinutes = (m: number) =>
    new Date(now.getTime() - m * 60 * 1000).toISOString()

export const MOCK_ORDERS: OrderDispatchData[] = [
    {
        id: 1,
        code: "599DFY",
        loading_name: "Jomboy",
        unloading_name: "Nukus",
        client_code: "100A",
        creator_name: "Shuxratjon Normatov",
        payment_types: ["cash", "transfer", "card"],
        created_through: 1,
        comment:
            "TTN: 515309524 TTN: 515309524 Napitka yuklanadi tent yoki ref fura navbati bilan yuklab chiqadi yaxshilab dagavor qilinglar mahsulot brakiga shafyor javobgar tenti butun bolsin Source location: Samarkand DD Distributor FAYZ AVANGARD MCHJ Route name: Samarkand-Karakalpakstan",
        date: "2026-05-20",
        created_at: isoMinusMinutes(20),
        dispatcher: null,
        criteria_list: [],
        is_paid: false,
        has_offer: false,
        is_blocked: false,
        is_commented: false,
        sub_status: 0,
        loading_id: 12,
        truck_id: "",
        full_name: "",
        phone_number: "",
    } as unknown as OrderDispatchData,
    {
        id: 2,
        code: "812ABC",
        loading_name: "Toshkent",
        unloading_name: "Buxoro",
        client_code: "80B",
        creator_name: "Akmal Karimov",
        payment_types: ["cash"],
        created_through: 2,
        comment: "Yengil yuk, 5 tonnagacha. Yuklab chiqishda diqqat.",
        date: "2026-05-21",
        created_at: isoMinusMinutes(45),
        dispatcher: null,
        criteria_list: [],
        is_paid: false,
        has_offer: false,
        is_blocked: false,
        is_commented: false,
        sub_status: 0,
        loading_id: 21,
        truck_id: "",
        full_name: "",
        phone_number: "",
    } as unknown as OrderDispatchData,
    {
        id: 3,
        code: "144KOR",
        loading_name: "Samarkand",
        unloading_name: "Andijon",
        client_code: "60C",
        creator_name: "Bobur Tursunov",
        payment_types: ["transfer", "card"],
        created_through: 3,
        comment:
            "Refrigerator, -18°C. Yuklab borgan haydovchi sovutgich holatini tekshirsin.",
        date: "2026-05-21",
        created_at: isoMinusMinutes(150),
        dispatcher: null,
        criteria_list: [],
        is_paid: false,
        has_offer: false,
        is_blocked: false,
        is_commented: false,
        sub_status: 0,
        loading_id: 34,
        truck_id: "",
        full_name: "",
        phone_number: "",
    } as unknown as OrderDispatchData,
    {
        id: 4,
        code: "276MNB",
        loading_name: "Qarshi",
        unloading_name: "Xorazm",
        client_code: "120D",
        creator_name: "Dilshod Otaboyev",
        payment_types: ["cash", "card"],
        created_through: 1,
        comment: "Don mahsulotlari. 30 tonna. Yopiq tent fura kerak.",
        date: "2026-05-22",
        created_at: isoMinusMinutes(10),
        dispatcher: null,
        criteria_list: [],
        is_paid: false,
        has_offer: false,
        is_blocked: false,
        is_commented: false,
        sub_status: 0,
        loading_id: 45,
        truck_id: "01A123BC",
        full_name: "Otaboyev Sherzod",
        phone_number: "+998 90 123 45 67",
    } as unknown as OrderDispatchData,
    {
        id: 5,
        code: "905QPR",
        loading_name: "Farg'ona",
        unloading_name: "Nukus",
        client_code: "200E",
        creator_name: "Elyor Mahmudov",
        payment_types: ["transfer"],
        created_through: 1,
        comment: "Mebel yuki. Avariya bo'lmasin uchun mahkam bog'lansin.",
        date: "2026-05-22",
        created_at: isoMinusMinutes(75),
        dispatcher: null,
        criteria_list: [],
        is_paid: false,
        has_offer: false,
        is_blocked: false,
        is_commented: false,
        sub_status: 0,
        loading_id: 56,
        truck_id: "01B456DE",
        full_name: "Karimov Akmal",
        phone_number: "+998 91 222 33 44",
    } as unknown as OrderDispatchData,
    {
        id: 6,
        code: "451STU",
        loading_name: "Navoiy",
        unloading_name: "Toshkent",
        client_code: "90F",
        creator_name: "Farxod Yo'ldoshev",
        payment_types: ["cash", "transfer"],
        created_through: 2,
        comment: "Sement qoplari. 20 tonna. Qishloq xo'jaligi do'koni.",
        date: "2026-05-23",
        created_at: isoMinusMinutes(200),
        dispatcher: null,
        criteria_list: [],
        is_paid: false,
        has_offer: false,
        is_blocked: false,
        is_commented: false,
        sub_status: 0,
        loading_id: 67,
        truck_id: "01C789FG",
        full_name: "Rustamov Diyor",
        phone_number: "+998 93 555 66 77",
    } as unknown as OrderDispatchData,
]
